Repository bcgsc/pori_ipr_client, pull requests merged in 2021-11, with the labels that each got.

#105 Change text content of appendix C
  app/views/ReportView/components/Appendices/components/GenomicReportOverview/index.tsx
Labels: documentation, enhancement

#110 Change size of immune images
  app/views/ReportView/components/Immune/index.scss
  app/views/ReportView/components/Immune/index.tsx
Labels: enhancement

#115 Feature/devsu 1671 add new expression images
  app/views/ReportView/components/ExpressionCorrelation/components/CorrelationPlot/index.tsx
  app/views/ReportView/components/ExpressionCorrelation/components/PlotByKey/index.tsx
  app/views/ReportView/components/ExpressionCorrelation/index.scss
  app/views/ReportView/components/ExpressionCorrelation/index.tsx
  package-lock.json
  package.json
Labels: enhancement

#112 Feature/devsu 1610 add tests to components
  .eslintrc.json
  app/App.tsx
  app/common.d.ts
  app/components/DataTable/__tests__/DataTable.test.tsx
  app/components/DataTable/__tests__/__snapshots__/DataTable.test.tsx.snap
  app/components/DataTable/__tests__/mockData.ts
  app/components/DataTable/components/ActionCellRenderer/__tests__/ActionCellRenderer.test.tsx
  app/components/DataTable/components/ActionCellRenderer/__tests__/__snapshots__/ActionCellRenderer.test.tsx.snap
  app/components/DataTable/components/ActionCellRenderer/index.tsx
  app/components/DataTable/components/ArrayCellRenderer/__tests__/ArrayCellRenderer.test.ts
  app/components/DataTable/components/ArrayCellRenderer/index.tsx
  app/components/DataTable/components/ColumnPicker/__tests__/ColumnPicker.test.tsx
  app/components/DataTable/components/ColumnPicker/__tests__/__snapshots__/ColumnPicker.test.tsx.snap
  app/components/DataTable/components/ColumnPicker/index.tsx
  app/components/DataTable/components/DetailDialog/__tests__/DetailDialog.test.tsx
  app/components/DataTable/components/DetailDialog/__tests__/__snapshots__/DetailDialog.test.tsx.snap
  app/components/DataTable/components/DetailDialog/index.tsx
  app/components/DataTable/components/EnsemblCellRenderer/index.tsx
  app/components/DataTable/components/GeneCellRenderer/__tests__/GeneCellRenderer.test.tsx
  app/components/DataTable/components/GeneCellRenderer/__tests__/__snapshots__/GeneCellRenderer.test.tsx.snap
  app/components/DataTable/components/GeneCellRenderer/index.tsx
  app/components/DataTable/components/GeneViewer/__tests__/GeneViewer.test.tsx
  app/components/DataTable/components/GeneViewer/__tests__/__snapshots__/GeneViewer.test.tsx.snap
  app/components/DataTable/components/GeneViewer/index.tsx
  app/components/DataTable/components/GeneViewer/types.d.ts
  app/components/DataTable/components/ImageViewer/__tests__/ImageViewer.test.tsx
  app/components/DataTable/components/ImageViewer/__tests__/__snapshots__/ImageViewer.test.tsx.snap
  app/components/DataTable/components/ImageViewer/index.tsx
  app/components/DataTable/components/ImageViewer/interfaces.ts
  app/components/DataTable/components/SvgViewer/__tests__/SvgViewer.test.tsx
  app/components/DataTable/components/SvgViewer/__tests__/__snapshots__/SvgViewer.test.tsx.snap
  app/components/DataTable/components/SvgViewer/index.tsx
  app/components/DataTable/index.tsx
  app/views/ReportView/components/CopyNumber/index.tsx
  app/views/ReportView/components/CopyNumber/types.d.ts
  app/views/ReportView/components/Expression/types.d.ts
  app/views/ReportView/components/SmallMutations/index.tsx
  app/views/ReportView/components/SmallMutations/types.d.ts
  app/views/ReportView/components/StructuralVariants/index.tsx
  app/views/ReportView/components/StructuralVariants/types.d.ts
  config/jest/windowEnvMock.js
Labels: documentation

#127 Bugfix/devsu 1689 fix routing when deployed to subfolder
  app/App.tsx
  app/components/Sidebar/__tests__/Sidebar.test.tsx
  app/components/Sidebar/index.tsx
  package-lock.json
  package.json
Labels: bug

#128 Add zenodo badge to README
  README.md
Labels: documentation
