Repository bcgsc/pori_ipr_client, pull requests merged in 2021-07, with the labels that each got.

#77 Enable cell text selection in germline reports
  app/views/GermlineView/components/Report/index.tsx
Labels: enhancement

#70 Feature/devsu 1535 make reports more clickable
  app/common.d.ts
  app/context/ReportContext/types.d.ts
  app/views/ReportsView/columnDefs.js
  app/views/ReportsView/components/LaunchCell/index.scss
  app/views/ReportsView/components/LaunchCell/index.tsx
  app/views/ReportsView/index.jsx
  app/views/ReportsView/index.tsx
Labels: enhancement

#76 Feature/devsu 1547 add sw cache busting
  app/App.tsx
  app/components/CacheBuster/index.tsx
  app/index.tsx
  app/registerServiceWorker.js
  app/services/management/auth.js
  app/statics/favicon/manifest.webmanifest
  app/views/MainView/index.tsx
  config/webpack/webpack.config.js
  config/webpack/webpack.docker.js
  config/webpack/webpack.prod.js
  package-lock.json
  package.json
Labels: bug, enhancement

#80 Extract style props from SVG
  app/components/SvgImage/index.tsx
Labels: bug, enhancement

#79 Feature/devsu 1565 add confirmation to delete slides
  app/components/AlertDialog/index.tsx
  app/views/ReportView/components/Slides/index.tsx
Labels: enhancement

#82 Release/v6.4.0
  README.md
  app/App.tsx
  app/common.d.ts
  app/components/AlertDialog/index.tsx
  app/components/CacheBuster/index.tsx
  app/components/DataTable/index.tsx
  app/components/PrintTable/index.scss
  app/components/PrintTable/index.tsx
  app/components/SvgImage/index.tsx
  app/context/ReportContext/types.d.ts
  app/index.tsx
  app/registerServiceWorker.js
  app/services/management/auth.js
  app/statics/favicon/manifest.webmanifest
  app/views/GermlineView/components/Report/index.tsx
  app/views/MainView/index.tsx
  app/views/PrintView/index.scss
  app/views/ReportView/components/AnalystComments/index.tsx
  app/views/ReportView/components/Appendices/components/ConfigTable/index.scss
  app/views/ReportView/components/Appendices/components/GenomicReportOverview/index.scss
  app/views/ReportView/components/Appendices/components/ProbeReportOverview/index.scss
  app/views/ReportView/components/Appendices/components/ProbeReportOverview/index.tsx
  app/views/ReportView/components/Appendices/index.scss
  app/views/ReportView/components/Appendices/index.tsx
  app/views/ReportView/components/CopyNumber/index.tsx
  app/views/ReportView/components/Discussion/index.tsx
  app/views/ReportView/components/ExpressionCorrelation/index.tsx
  app/views/ReportView/components/GenomicSummary/index.tsx
  app/views/ReportView/components/Immune/index.tsx
  app/views/ReportView/components/KbMatches/index.tsx
  app/views/ReportView/components/Microbial/index.tsx
  app/views/ReportView/components/MutationBurden/index.tsx
  app/views/ReportView/components/MutationSignatures/index.tsx
  app/views/ReportView/components/PathwayAnalysis/index.tsx
  app/views/ReportView/components/Pharmacogenomic/columnDefs.ts
  app/views/ReportView/components/Pharmacogenomic/index.tsx
  app/views/ReportView/components/ProbeSummary/index.scss
  app/views/ReportView/components/ProbeSummary/index.tsx
  app/views/ReportView/components/Settings/index.tsx
  app/views/ReportView/components/Slides/index.tsx
  app/views/ReportView/components/SmallMutations/index.tsx
  app/views/ReportView/components/StructuralVariants/index.tsx
  app/views/ReportView/components/TherapeuticTargets/index.tsx
  app/views/ReportView/index.jsx
  app/views/ReportView/sections.js
  app/views/ReportsView/columnDefs.js
  app/views/ReportsView/components/LaunchCell/index.scss
  app/views/ReportsView/components/LaunchCell/index.tsx
  app/views/ReportsView/index.jsx
  app/views/ReportsView/index.tsx
  app/views/TemplateView/sections.js
  config/webpack/webpack.config.js
  config/webpack/webpack.docker.js
  config/webpack/webpack.prod.js
  package-lock.json
  package.json
Labels: release

#78 Feature/devsu 1551 investigate print numbering
  app/components/PageBreak/index.jsx
  app/components/PageBreak/index.scss
  app/components/PageBreak/index.tsx
  app/index.css
  app/views/PrintView/components/RunningCenter/index.tsx
  app/views/PrintView/components/RunningLeft/index.tsx
  app/views/PrintView/components/RunningRight/index.tsx
  app/views/PrintView/index.scss
  app/views/PrintView/index.tsx
  app/views/ReportView/components/AnalystComments/index.scss
  app/views/ReportView/components/Appendices/index.tsx
  app/views/ReportView/components/PathwayAnalysis/components/Pathway/index.tsx
  app/views/ReportView/components/TherapeuticTargets/components/PrintTables/index.scss
  app/views/ReportView/components/TherapeuticTargets/index.tsx
  config/webpack/webpack.config.js
  package-lock.json
  package.json
Labels: enhancement

#83 Fix docs
  README.md
Labels: bug

#86 Release/v6.4.1
  app/components/SvgImage/index.tsx
Labels: bug, release

#87 v6.4.1
  package-lock.json
  package.json
Labels: release

#84 Add demo description bubbles to core variant pages
  app/components/DataTable/index.tsx
  app/components/DemoDescription/index.tsx
  app/views/ReportView/components/CopyNumber/index.tsx
  app/views/ReportView/components/Expression/index.jsx
  app/views/ReportView/components/SmallMutations/index.tsx
  app/views/ReportView/components/StructuralVariants/index.tsx
Labels: documentation

#81 Feature/devsu 1570 add source column to kb matches
  app/components/DataTable/components/CivicCellRenderer/__tests__/CivicCellRenderer.test.tsx
  app/components/DataTable/components/CivicCellRenderer/index.tsx
  app/components/DataTable/components/EnsemblCellRenderer/index.tsx
  app/components/DataTable/components/SvgViewer/columnDefs.js
  app/components/DataTable/components/SvgViewer/index.jsx
  app/components/DataTable/index.tsx
  app/components/NewTabLink/index.scss
  app/components/NewTabLink/index.tsx
  app/views/ReportView/components/KbMatches/columnDefs.ts
  tsconfig.json
Labels: enhancement
