Repository bcgsc/pori_ipr_client, pull requests merged in 2021-04, with the labels that each got.

#47 Add link to main pori repo
  README.md
Labels: documentation

#43 Bugfix/devsu 1473 fix service worker registration
  config/webpack/webpack.prod.js
  package-lock.json
  package.json
Labels: enhancement

#40 Feature/devsu 1416 pathway legend updates
  .eslintrc.json
  app/components/AsyncButton/index.scss
  app/components/AsyncButton/index.tsx
  app/components/Image/index.scss
  app/components/Image/index.tsx
  app/components/SvgImage/index.scss
  app/components/SvgImage/index.tsx
  app/root.module.js
  app/views/PrintView/index.scss
  app/views/ReportView/components/PathwayAnalysis/components/Legend/index.tsx
  app/views/ReportView/components/PathwayAnalysis/components/Pathway/index.tsx
  app/views/ReportView/components/PathwayAnalysis/index.js
  app/views/ReportView/components/PathwayAnalysis/index.scss
  app/views/ReportView/components/PathwayAnalysis/index.tsx
  app/views/ReportView/components/PathwayAnalysis/pathway-analysis-edit.pug
  app/views/ReportView/components/PathwayAnalysis/pathway-analysis.pug
  app/views/ReportView/components/PathwayAnalysis/types.d.ts
  package-lock.json
  package.json
  statics/images/pathway_legend_v1.png
  statics/images/pathway_legend_v2.png
Labels: enhancement

#46 Feature/devsu 1469 ref alt in tgr
  app/common.d.ts
  app/components/PrintTable/index.scss
  app/components/PrintTable/index.tsx
  app/components/ReportContext/index.ts
  app/components/ReportContext/interfaces.ts
  app/components/ReportContext/types.d.ts
  app/views/ReportView/components/Appendices/index.scss
  app/views/ReportView/components/MutationSignatures/index.tsx
  app/views/ReportView/components/MutationSignatures/types.d.ts
  app/views/ReportView/components/ProbeSummary/columnDefs.ts
  app/views/ReportView/components/ProbeSummary/components/PrintTable/index.tsx
  app/views/ReportView/components/ProbeSummary/components/TestInformation/index.tsx
  app/views/ReportView/components/ProbeSummary/components/TestInformation/types.d.ts
  app/views/ReportView/components/ProbeSummary/index.scss
  app/views/ReportView/components/ProbeSummary/index.tsx
  app/views/ReportView/components/ProbeSummary/types.d.ts
Labels: enhancement

#48 Feature/devsu 1493 refactor microbial to use react
  app/root.module.js
  app/views/ReportView/components/Microbial/index.js
  app/views/ReportView/components/Microbial/index.scss
  app/views/ReportView/components/Microbial/index.tsx
  app/views/ReportView/components/Microbial/microbial.pug
Labels: enhancement

#44 Feature/devsu 1431 add msi data to summary
  app/components/ReportContext/index.ts
  app/components/ReportContext/types.d.ts
  app/components/SignatureCard/index.tsx
  app/views/ReportView/components/Appendices/components/ConfigTable/index.tsx
  app/views/ReportView/components/GenomicSummary/index.tsx
  app/views/ReportView/components/GenomicSummary/types.d.ts
  app/views/ReportView/components/Immune/index.tsx
  app/views/ReportView/components/Immune/types.d.ts
  app/views/ReportView/components/MutationSignatures/index.tsx
  config/jest/jest.config.js
  config/webpack/webpack.config.js
Labels: enhancement

#45 Feature/devsu 1487 use react in presentation sections
  .eslintrc.json
  app/components/Paginate/index.js
  app/components/Paginate/index.scss
  app/components/Paginate/paginate.pug
  app/index.scss
  app/root.module.js
  app/services/reports/slides.service.js
  app/views/PrintView/index.tsx
  app/views/ReportView/components/AnalystComments/components/TextEditor/__tests__/TextEditor.test.tsx
  app/views/ReportView/components/Discussion/components/AddComment/__tests__/AddComment.test.tsx
  app/views/ReportView/components/Discussion/components/AddComment/index.scss
  app/views/ReportView/components/Discussion/components/AddComment/index.tsx
  app/views/ReportView/components/Discussion/components/CommentCard/__tests__/CommentCard.test.tsx
  app/views/ReportView/components/Discussion/components/CommentCard/index.scss
  app/views/ReportView/components/Discussion/components/CommentCard/index.tsx
  app/views/ReportView/components/Discussion/components/CommentCard/types.d.ts
  app/views/ReportView/components/Discussion/components/DiscussionEntry/discussion-entry.pug
  app/views/ReportView/components/Discussion/components/DiscussionEntry/index.js
  app/views/ReportView/components/Discussion/components/DiscussionEntry/index.scss
  app/views/ReportView/components/Discussion/discussion.pug
  app/views/ReportView/components/Discussion/index.js
  app/views/ReportView/components/Discussion/index.scss
  app/views/ReportView/components/Discussion/index.tsx
  app/views/ReportView/components/Slides/components/UploadSlide/__tests__/UploadSlide.test.tsx
  app/views/ReportView/components/Slides/components/UploadSlide/index.scss
  app/views/ReportView/components/Slides/components/UploadSlide/index.tsx
  app/views/ReportView/components/Slides/index.js
  app/views/ReportView/components/Slides/index.scss
  app/views/ReportView/components/Slides/index.tsx
  app/views/ReportView/components/Slides/slides.pug
  app/views/ReportView/components/Slides/slides.scss
  app/views/ReportView/components/Slides/types.d.ts
  package-lock.json
  package.json
Labels: enhancement

#52 Fix copy plot image cut off
  app/views/ReportView/components/CopyNumber/index.tsx
Labels: bug
