Repository bcgsc/pori_ipr_client, pull requests merged in 2021-02, with the labels that each got.

#1 Feature/dockerize
  .dockerignore
  .github/workflows/docker-publish.yml
  .github/workflows/npm-test.yml
  .npmrc
  Dockerfile
  README.md
  app/App.tsx
  app/components/DataTable/components/GeneViewer/index.jsx
  app/components/DataTable/index.tsx
  app/components/hooks/useGrid.ts
  app/views/AdminView/components/Groups/index.tsx
  app/views/AdminView/components/Projects/index.tsx
  app/views/AdminView/components/Users/index.tsx
  app/views/PatientsView/index.jsx
  app/views/ReportView/components/GenomicSummary/index.tsx
  app/views/ReportView/components/MutationSignatures/index.jsx
  app/views/ReportView/components/TherapeuticTargets/components/PrintTables/index.jsx
  app/views/ReportView/components/TherapeuticTargets/index.tsx
  app/views/ReportView/index.jsx
  config/nginx.conf
  config/webpack/webpack.docker.js
  package-lock.json
  package.json
Labels: devops

#5 Change label to 'CD8+ T Cell Score'
  app/views/ReportView/components/GenomicSummary/index.tsx
Labels: enhancement

#6 Add percent sign to tumour content fields
  app/views/ReportView/components/GenomicSummary/components/TumourSummaryEdit/index.tsx
  app/views/ReportView/components/GenomicSummary/index.tsx
Labels: enhancement

#4 Feature/devsu 1425 use templates for client
  app/components/ReportSidebar/index.jsx
  app/components/Sidebar/sidebar.pug
  app/services/api/api.tsx
  app/services/api/index.ts
  app/views/MainView/index.tsx
  app/views/ReportView/components/Settings/index.js
  app/views/ReportView/components/Settings/report-settings.pug
  app/views/ReportView/index.jsx
  app/views/TemplateView/columnDefs.ts
  app/views/TemplateView/components/AddEditTemplate/index.scss
  app/views/TemplateView/components/AddEditTemplate/index.tsx
  app/views/TemplateView/index.tsx
  app/views/TemplateView/sections.js
Labels: enhancement

#8 Display sample field in genomic events table
  app/views/ReportView/components/ProbeSummary/columnDefs.ts
Labels: enhancement

#9 Feature/subdir deploy
  .gitignore
  app/App.tsx
  app/index.tsx
  app/publicPath.js
  app/services/SnackbarUtils.tsx
  app/services/api/api.tsx
  config/.env
  config/env.sh
  config/webpack/webpack.config.js
  config/webpack/webpack.dev.js
  config/webpack/webpack.docker.js
  config/webpack/webpack.local.js
  config/webpack/webpack.prod.js
  config/webpack/webpack.staging.js
  statics/index.ejs
  statics/ipr-env-config.js
Labels: devops

#7 Feature/devsu 1430 display msi scatter plot
  app/components/DataTable/index.tsx
  app/views/ReportView/components/MutationBurden/columnDefs.ts
  app/views/ReportView/components/MutationBurden/index.tsx
  app/views/ReportView/components/MutationBurden/types.d.ts
  tsconfig.json
Labels: enhancement

#11 Bugfix/devsu 1442 some angular tables not rendering
  app/components/DataTable/index.tsx
  app/views/ReportView/components/SmallMutations/index.js
  app/views/ReportView/components/SmallMutations/small-mutations.pug
Labels: bug

#12 Feature/devsu 1440 move test information
  app/views/ReportView/components/GenomicSummary/index.tsx
  app/views/ReportView/components/ProbeSummary/index.tsx
Labels: enhancement

#13 Change sex label to gender
  app/views/ReportView/components/GenomicSummary/components/PatientEdit/index.jsx
  app/views/ReportView/components/GenomicSummary/index.tsx
  app/views/ReportView/components/ProbeSummary/index.tsx
Labels: enhancement

#15 Feature/devsu 1360 default mutation signature
  app/views/ReportView/components/GenomicSummary/components/PatientEdit/index.jsx
  app/views/ReportView/components/GenomicSummary/index.tsx
Labels: enhancement

#10 Feature/devsu 1403 refactor germline reports page
  app/common.d.ts
  app/root.module.js
  app/views/GermlineView/components/Board/columnDefs.js
  app/views/GermlineView/components/Board/components/ApiPaginatedTable/components/CheckboxCell/index.scss
  app/views/GermlineView/components/Board/components/ApiPaginatedTable/components/CheckboxCell/index.tsx
  app/views/GermlineView/components/Board/components/ApiPaginatedTable/components/PaginationPanel/index.scss
  app/views/GermlineView/components/Board/components/ApiPaginatedTable/components/PaginationPanel/index.tsx
  app/views/GermlineView/components/Board/components/ApiPaginatedTable/components/ReviewFilter/index.tsx
  app/views/GermlineView/components/Board/components/ApiPaginatedTable/index.scss
  app/views/GermlineView/components/Board/components/ApiPaginatedTable/index.tsx
  app/views/GermlineView/components/Board/components/ParamsContext/index.ts
  app/views/GermlineView/components/Board/germline-board.pug
  app/views/GermlineView/components/Board/index.js
  app/views/GermlineView/components/Board/index.scss
  app/views/GermlineView/components/Board/index.tsx
  app/views/GermlineView/components/Report/index.scss
  app/views/GermlineView/types.d.ts
Labels: enhancement

#17 Set checkLoginIframe to false
  app/services/management/auth.js
Labels: bug

#18 Update genomic appendix methods text
  app/views/ReportView/components/Appendices/components/GenomicReportOverview/index.tsx
Labels: enhancement

#21 Fix accessor for scatter plot
  app/views/ReportView/components/MutationBurden/index.tsx
Labels: bug

#25 Bugfix/devsu 1450 fix msi scatter
  app/components/AuthenticatedRoute/index.jsx
  app/components/Image/index.scss
  app/components/Image/index.tsx
  app/components/ReportSidebar/index.jsx
  app/views/ReportView/components/MutationBurden/index.scss
  app/views/ReportView/components/MutationBurden/index.tsx
Labels: bug

#27 Fix keycloak login throwing error in success method
  app/services/management/auth.js
  app/views/LoginView/index.jsx
Labels: bug

#28 Access react window instead of angular window
  app/components/Sidebar/index.js
  app/components/Sidebar/sidebar.pug
Labels: bug
