Repository bcgsc/pori_ipr_client, pull requests merged in 2024-07, with the labels that each got.

#518 bugfix/DEVSU-2367 Bullet Points Missing in Analyst Comments
  app/index.scss
Labels: bug

#516 bugfix/DEVSU-2369 Disable "Add to Potential Therapeutic Targets" Options for KB Matches Clinical Trials
  app/components/DataTable/components/KbMatchesActionCellRenderer/index.tsx
Labels: bug

#521 bugfix/ Small typo fix for add edit variant text
  app/views/AdminView/components/VariantText/components/AddEditVariantText/index.tsx
Labels: bug

#528 [DEVSU-2362 2377 2396] tumour summary edit bugfixes
  app/components/NavBar/components/UserSettingsDialog/index.tsx
  app/components/TumourSummaryEdit/index.tsx
  app/utils/getMicbSiteIntegrationStatusLabel.ts
  app/views/PrintView/index.tsx
  app/views/ReportView/components/GenomicSummary/index.tsx
  app/views/ReportView/components/PatientInformation/index.tsx
  app/views/ReportView/components/RapidSummary/index.tsx
  app/views/ReportView/components/TumourSummary/index.tsx
Labels: bug, enhancement

#527 bugfix/DEVSU-2392 fix null recruitment status error for old reports without kbData property
  app/components/DataTable/components/KbMatchesActionCellRenderer/index.tsx
Labels: bug

#526 [DEVSU-2376] add table option to mount popup div to body instead
  app/components/DataTable/index.tsx
Labels: bug

#537 bugfix/DEVSU-2399 fix reportSampleInfo acquisition
  app/views/ReportView/components/PatientInformation/index.tsx
  app/views/ReportView/components/PharmacoGenomicSummary/index.tsx
  app/views/ReportView/components/ProbeSummary/index.tsx
Labels: bug

#534 feat/DEVSU-2389 update groups detailed view
  app/components/DataTable/components/DetailDialog/index.tsx
Labels: enhancement

#510 Feat/DEVSU-2247 Add Search Reports by Variant Feature
  app/components/DataTable/index.tsx
  app/components/ReportsTable/searchColumnDefs.ts
  app/components/Sidebar/index.tsx
  app/custom.d.ts
  app/utils/searchReportsColumns.js
  app/views/MainView/index.tsx
  app/views/ReportsByVariantView/index.scss
  app/views/ReportsByVariantView/index.tsx
  app/views/SearchView/index.scss
  app/views/SearchView/index.tsx
  tsconfig.json
Labels: enhancement

#540 Bugfix/DEVSU-2401 report assignment access
  app/context/ResourceContext/index.tsx
  app/context/ResourceContext/types.d.ts
  app/views/ReportView/components/Settings/components/AddUserCard/index.tsx
  app/views/ReportView/components/Settings/components/AssociationCard/index.tsx
Labels: bug

#541 [DEVSU-2402] update handler on Groups/AddEditUserDialog
  app/views/AdminView/components/Groups/components/AddEditGroupDialog/index.tsx
Labels: bug

#545 [DEVSU-2408] add report rule to allow edit on report state
  app/context/ResourceContext/index.tsx
  app/views/ReportView/components/Settings/index.tsx
  app/views/ReportView/index.tsx
Labels: bug
