Repository bcgsc/pori_ipr_client, pull requests merged in 2024-02, with the labels that each got.

#413 [DEVSU-2165] new project user undefined
  app/components/ReportAutocomplete/index.tsx
  app/components/UserAutocomplete/index.tsx
  app/views/ProjectsView/components/AddEditProjectDialog/index.tsx
Labels: bug

#419 v6.26.0
  .eslintrc.js
  .github/workflows/clininfoonrelease.yml
  app/components/AuthenticatedRoute/index.jsx
  app/components/IPRWYSIWYGEditor/index.tsx
  app/components/NavBar/index.tsx
  app/components/ReportAutocomplete/index.tsx
  app/components/TumourSummaryEdit/index.tsx
  app/components/UserAutocomplete/index.tsx
  app/context/ReportContext/types.d.ts
  app/context/ResourceContext/index.tsx
  app/context/ResourceContext/types.d.ts
  app/context/SecurityContext/index.js
  app/context/SecurityContext/index.tsx
  app/context/UserContext/index.tsx
  app/hooks/useConfirmDialog.tsx
  app/hooks/useExternalMode.ts
  app/hooks/useSecurity.tsx
  app/utils/checkAccess.ts
  app/views/LoginView/index.tsx
  app/views/MainView/index.tsx
  app/views/ProjectsView/components/AddEditProjectDialog/index.tsx
  app/views/ReportView/components/Appendices/components/ReportOverview/__tests__/ReportOverview.test.tsx
  app/views/ReportView/components/Appendices/components/ReportOverview/index.scss
  app/views/ReportView/components/Appendices/components/ReportOverview/index.tsx
  app/views/ReportView/components/Appendices/index.tsx
  app/views/ReportView/components/Discussion/components/CommentCard/index.tsx
  app/views/ReportView/components/GenomicSummary/index.tsx
  app/views/ReportView/components/RapidSummary/index.tsx
  app/views/ReportView/components/Settings/components/Analysis/index.tsx
  app/views/ReportView/index.tsx
  create-jira-ticket.js
  package-lock.json
  package.json
Labels: release

#420 feat/DEVSU-2188-add-recruitment-status
  app/common.d.ts
  app/views/ReportView/components/KbMatches/columnDefs.ts
Labels: enhancement

#423 [DEVSU-2179] report specific appendix part 2
  app/components/SignatureCard/SignatureCard.stories.tsx
  app/components/SignatureCard/__tests__/SignatureCard.test.tsx
  app/components/SignatureCard/index.tsx
  app/context/ReportContext/index.ts
  app/context/ReportContext/types.d.ts
  app/context/ResourceContext/index.tsx
  app/context/UserContext/index.tsx
  app/context/UserContext/interfaces.ts
  app/hooks/useReport.tsx
  app/utils/checkAccess.ts
  app/views/MainView/index.tsx
  app/views/ProjectsView/index.tsx
  app/views/ReportView/components/AnalystComments/index.tsx
  app/views/ReportView/components/Appendices/index.tsx
  app/views/ReportView/components/GenomicSummary/index.tsx
  app/views/ReportView/components/KbMatches/index.tsx
  app/views/ReportView/components/MutationSignatures/index.tsx
  app/views/ReportView/components/PathwayAnalysis/components/Legend/index.tsx
  app/views/ReportView/components/PathwayAnalysis/components/Pathway/index.tsx
  app/views/ReportView/components/PharmacoGenomicSummary/index.tsx
  app/views/ReportView/components/ProbeSummary/index.tsx
  app/views/ReportView/components/RapidSummary/index.tsx
  app/views/ReportView/components/Settings/components/AddUserCard/index.tsx
  app/views/ReportView/components/Settings/components/AssociationCard/index.tsx
  app/views/ReportView/components/Settings/index.tsx
  app/views/ReportView/components/Slides/components/Slide/__tests__/Slide.test.tsx
  app/views/ReportView/components/Slides/components/Slide/index.tsx
  app/views/ReportView/components/Slides/index.tsx
  app/views/ReportView/components/TherapeuticTargets/index.tsx
  app/views/ReportView/index.tsx
Labels: bug, enhancement, security

#424 Release/v6.27.0
  app/common.d.ts
  app/components/IPRWYSIWYGEditor/index.tsx
  app/components/SignatureCard/SignatureCard.stories.tsx
  app/components/SignatureCard/__tests__/SignatureCard.test.tsx
  app/components/SignatureCard/index.tsx
  app/context/ReportContext/index.ts
  app/context/ReportContext/types.d.ts
  app/context/ResourceContext/index.tsx
  app/context/UserContext/index.tsx
  app/context/UserContext/interfaces.ts
  app/hooks/useReport.tsx
  app/utils/checkAccess.ts
  app/views/MainView/index.tsx
  app/views/ProjectsView/index.tsx
  app/views/ReportView/components/AnalystComments/index.tsx
  app/views/ReportView/components/Appendices/index.tsx
  app/views/ReportView/components/GenomicSummary/index.tsx
  app/views/ReportView/components/KbMatches/columnDefs.ts
  app/views/ReportView/components/KbMatches/index.tsx
  app/views/ReportView/components/MutationSignatures/index.tsx
  app/views/ReportView/components/PathwayAnalysis/components/Legend/index.tsx
  app/views/ReportView/components/PathwayAnalysis/components/Pathway/index.tsx
  app/views/ReportView/components/PharmacoGenomicSummary/index.tsx
  app/views/ReportView/components/ProbeSummary/index.tsx
  app/views/ReportView/components/RapidSummary/index.tsx
  app/views/ReportView/components/Settings/components/AddUserCard/index.tsx
  app/views/ReportView/components/Settings/components/AssociationCard/index.tsx
  app/views/ReportView/components/Settings/index.tsx
  app/views/ReportView/components/Slides/components/Slide/__tests__/Slide.test.tsx
  app/views/ReportView/components/Slides/components/Slide/index.tsx
  app/views/ReportView/components/Slides/index.tsx
  app/views/ReportView/components/TherapeuticTargets/index.tsx
  app/views/ReportView/index.tsx
  package-lock.json
  package.json
Labels: release

#428 bugfix/DEVSU-2224-setting-and-sign-missing
  app/context/ResourceContext/index.tsx
Labels: bug

#429 Release/v6.27.1
  app/context/ResourceContext/index.tsx
  package-lock.json
  package.json
Labels: release

#425 Bugfix/DEVSU-2194-retain-report-text-formatting
  app/components/PrintTable/index.scss
  app/views/ReportView/components/AnalystComments/index.scss
  app/views/ReportView/components/Appendices/index.scss
  app/views/ReportView/components/GenomicSummary/index.tsx
Labels: bug
