Repository bcgsc/pori_ipr_client, pull requests merged in 2025-04, with the labels that each got.

#627 Bugfix/devsu 2623 cancer pred fix
  app/components/DataTable/components/ArrayCellRenderer/index.tsx
  app/views/ReportView/components/CancerPredisposition/columnDefs.ts
Labels: bug

#626 v7.0.2
  app/components/DataTable/components/ArrayCellRenderer/index.tsx
  app/utils/kbMatchStatementsGeneValueGetter.ts
  app/utils/kbMatchStatementsKnownVarValueGetter.ts
  app/utils/kbMatchStatementsObsVarValueGetter.ts
  app/views/ReportView/components/CancerPredisposition/columnDefs.ts
  app/views/ReportView/components/KbMatches/coalesce.ts
  package-lock.json
  package.json
Labels: bug, release

#618 DEVSU-2593, DEVSU-2493 IPR Client Search Rework
  app/components/DataTable/components/CustomSetFilter/index.scss
  app/components/DataTable/components/CustomSetFilter/index.tsx
  app/components/DataTable/index.tsx
  app/components/ReportsTable/searchColumnDefs.ts
  app/constants/index.js
  app/index.scss
  app/utils/searchReportsColumns.js
  app/views/MainView/index.tsx
  app/views/ReportsByVariantView/index.scss
  app/views/ReportsByVariantView/index.tsx
  app/views/ReportsSearchView/index.scss
  app/views/ReportsSearchView/index.tsx
  app/views/SearchView/index.tsx
Labels: enhancement

#621 - DEVSU-2547 Display 'context' column in potential resistance and toxicity table
  app/views/ReportView/components/TherapeuticTargets/columnDefs.js
  app/views/ReportView/components/TherapeuticTargets/index.tsx
Labels: enhancement

#622 -DEVSU-2583 Update user creation/editing to use react-query
  app/views/AdminView/components/Users/index.tsx
Labels: enhancement

#638 DEVSU-2638 Set key variant as default search category
  app/views/ReportView/components/TherapeuticTargets/columnDefs.js
  app/views/SearchView/index.tsx
Labels: enhancement

#639 DEVSU-2638 Key Variant as Default Search Category
  app/views/ReportView/components/TherapeuticTargets/columnDefs.js
  app/views/SearchView/index.tsx
Labels: enhancement
