Repository bcgsc/pori_ipr_client, pull requests merged in 2025-03, with the labels that each got.

#609 DEVSU-2597 Fix undefined 'kbmatchTag' error in kb matches view
  app/components/DataTable/components/KbMatchesActionCellRenderer/index.tsx
Labels: bug

#611 DEVSU-2591 Using searchbar on IPR genomic report KB match page makes page go blank
  app/utils/getGeneProp.js
  app/views/ReportView/components/CancerPredisposition/columnDefs.ts
  app/views/ReportView/components/KbMatches/columnDefs.ts
  app/views/ReportView/components/Pharmacogenomic/columnDefs.ts
Labels: bug

#613 bugfix: reset editor state onClose for IPRWYSIWYGEditor
  app/components/IPRWYSIWYGEditor/index.tsx
Labels: bug

#606 Release/v7.0.1
  app/App.tsx
  app/common.d.ts
  app/components/DataTable/components/ArrayCellRenderer/index.tsx
  app/components/DataTable/components/KbMatchesActionCellRenderer/index.tsx
  app/components/IPRWYSIWYGEditor/index.tsx
  app/utils/getGeneProp.js
  app/utils/kbMatchStatementsGeneValueGetter.ts
  app/utils/kbMatchStatementsKnownVarValueGetter.ts
  app/utils/kbMatchStatementsObsVarValueGetter.ts
  app/views/ReportView/components/AnalystComments/index.tsx
  app/views/ReportView/components/CancerPredisposition/columnDefs.ts
  app/views/ReportView/components/KbMatches/columnDefs.ts
  app/views/ReportView/components/PharmacoGenomicSummary/columnDefs.ts
  app/views/ReportView/components/Pharmacogenomic/columnDefs.ts
  app/views/ReportView/components/Pharmacogenomic/index.tsx
  app/views/ReportView/components/TherapeuticTargets/components/AutocompleteHandler/index.tsx
  app/views/ReportView/components/TherapeuticTargets/components/EditDialog/index.tsx
  app/views/ReportView/components/TherapeuticTargets/index.tsx
  app/views/TemplateView/index.tsx
  package-lock.json
  package.json
Labels: release

#620 DEVSU-2603 Fix kbMatchedStatements coalesce logic
  app/utils/kbMatchStatementsGeneValueGetter.ts
  app/utils/kbMatchStatementsKnownVarValueGetter.ts
  app/utils/kbMatchStatementsObsVarValueGetter.ts
  app/views/ReportView/components/KbMatches/coalesce.ts
Labels: bug, enhancement
